"""Phase 4 AI Test Generation schemas and QA Matrix definitions."""
from __future__ import annotations

from typing import Literal, Any
from pydantic import Field, field_validator, model_validator

from testq_browser.test_schemas import (
    StrictModel,
    UITestDefinition,
    APITestDefinition,
)

# Controlled QA Test Matrix Categories
QA_CATEGORIES = (
    "navigation",
    "authentication",
    "forms",
    "validation",
    "inputs",
    "buttons",
    "selects",
    "checkboxes",
    "radio_controls",
    "api",
    "error_handling",
    "boundary_values",
    "empty_states",
    "required_fields",
    "workflow",
)

QACategory = Literal[
    "navigation",
    "authentication",
    "forms",
    "validation",
    "inputs",
    "buttons",
    "selects",
    "checkboxes",
    "radio_controls",
    "api",
    "error_handling",
    "boundary_values",
    "empty_states",
    "required_fields",
    "workflow",
]


class TestStrategyItem(StrictModel):
    """A strategic test target identified by the AI Test Planner."""
    __test__ = False
    id: str = Field(pattern=r"^STRAT-[0-9]{3,}$")
    category: QACategory
    target: str = Field(min_length=1, max_length=2000)
    description: str = Field(min_length=1, max_length=1000)
    risk_level: Literal["critical", "high", "medium", "low"] = "medium"
    priority: Literal["critical", "high", "medium", "low"] = "medium"

    @field_validator("target")
    @classmethod
    def relative_target_only(cls, v: str) -> str:
        if v.startswith(("http://", "https://")):
            raise ValueError("Target path must be relative to local application, not an absolute URL")
        if v.startswith("//"):
            raise ValueError("Protocol-relative URLs are prohibited")
        if not v.startswith("/"):
            raise ValueError("Target must start with '/'")
        return v


class TestStrategy(StrictModel):
    """The structured strategy produced by the AI Test Planner."""
    __test__ = False
    summary: str = Field(max_length=2000)
    items: list[TestStrategyItem] = Field(default_factory=list, max_length=50)

    @field_validator("items", mode="before")
    @classmethod
    def drop_external_items(cls, items: Any) -> Any:
        if not isinstance(items, list):
            return items
        safe = []
        for it in items:
            if isinstance(it, dict):
                tgt = str(it.get("target", ""))
                if tgt.startswith(("http://", "https://", "//")):
                    continue
            safe.append(it)
        return safe


class AITestGenerationOutput(StrictModel):
    """Structured test suite generated by the AI Test Generator."""
    __test__ = False
    ui_tests: list[dict[str, Any]] = Field(default_factory=list, max_length=50)
    api_tests: list[dict[str, Any]] = Field(default_factory=list, max_length=50)

    @model_validator(mode="before")
    @classmethod
    def normalize_test_container(cls, data: Any) -> Any:
        ui: list[dict[str, Any]] = []
        api: list[dict[str, Any]] = []

        def add_item(item: Any):
            if not isinstance(item, dict):
                return
            if item.get("type") == "api" or "request" in item or ("method" in item and "path" in item):
                api.append(item)
            else:
                ui.append(item)

        if isinstance(data, list):
            for item in data:
                add_item(item)
            return {"ui_tests": ui, "api_tests": api}

        if isinstance(data, dict):
            # Check if there are explicit ui_tests / api_tests
            if "ui_tests" in data and isinstance(data["ui_tests"], list):
                for item in data["ui_tests"]:
                    add_item(item)
            if "api_tests" in data and isinstance(data["api_tests"], list):
                for item in data["api_tests"]:
                    add_item(item)

            # Check alternative list keys
            for alt_key in ("tests", "test_cases", "generated_tests", "suite", "cases", "ui", "api"):
                if alt_key in data and isinstance(data[alt_key], list):
                    for item in data[alt_key]:
                        add_item(item)

            # Check if dict keys themselves are test objects: e.g. "test_1": {...}, "case_1": {...}
            for k, v in data.items():
                if k in ("ui_tests", "api_tests", "tests", "test_cases", "generated_tests", "suite", "cases", "ui", "api"):
                    continue
                if isinstance(v, dict):
                    if any(term in v for term in ("steps", "action", "target", "request", "name", "title", "expected")):
                        if not v.get("id"):
                            v["id"] = k
                        add_item(v)

            return {"ui_tests": ui, "api_tests": api}

        return data

