"""Phase 3 deterministic test definitions — re-exported from testq_browser.test_schemas."""
from testq_browser.test_schemas import (
    StrictModel,
    SelectorSpec,
    UITestStep,
    UIAssertion,
    UITestDefinition,
    APIRequestSpec,
    APIAssertion,
    APITestDefinition,
    TestDefinition,
    validate_test_definition,
    TestResultStatus,
    AssertionResult,
    StepResult,
    TestExecutionResult,
    TestArtifact,
    _TEST_EVIDENCE_KINDS,
    _SAFE_METHODS,
    _SAFE_HEADER_NAMES,
)

__all__ = [
    "StrictModel",
    "SelectorSpec",
    "UITestStep",
    "UIAssertion",
    "UITestDefinition",
    "APIRequestSpec",
    "APIAssertion",
    "APITestDefinition",
    "TestDefinition",
    "validate_test_definition",
    "TestResultStatus",
    "AssertionResult",
    "StepResult",
    "TestExecutionResult",
    "TestArtifact",
    "_TEST_EVIDENCE_KINDS",
    "_SAFE_METHODS",
    "_SAFE_HEADER_NAMES",
]
